apiVersion: v1
kind: Service
metadata:
  name: {{ include "arch-next.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "arch-next.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app.kubernetes.io/name: {{ include "arch-next.name" . }}
