replicaCount: 2

image:
  repository: arch-next
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

readinessProbe:
  path: /
  port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5

livenessProbe:
  path: /
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10