apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arch-next
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Stephen-Ibe/devops-lab
    targetRevision: HEAD
    path: apps/arch-next/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true